CREATE DATABASE AlpineShipping;

CREATE TABLE Client(
ClientID int AUTO_INCREMENT,
BusinessName varchar(50) NOT NULL,
CONSTRAINT PRIMARY KEY (ClientID)
);

CREATE TABLE Carrier(
CarrierID INT AUTO_INCREMENT,
CarrierName varchar(20) NOT NULL,
TrackingSite varchar(60),
CONSTRAINT PRIMARY KEY (CarrierID)
);

CREATE TABLE Shipment(
ShipmentID INT AUTO_INCREMENT,
ClientID INT NOT NULL,
CarrierID INT NOT NULL,
ItemsShipping varchar (100) NOT NULL,
EstShipDate DATE,
EstDelivery DATE,
TrackingNum VARCHAR(30) NOT NULL,
Status VARCHAR(10) NOT NULL,
Notes VARCHAR(100),
DateEntered DATE,
CONSTRAINT PRIMARY KEY (ShipmentID),
CONSTRAINT FOREIGN KEY (ClientID) REFERENCES Client(ClientID) ON DELETE CASCADE,
CONSTRAINT FOREIGN KEY (CarrierID) REFERENCES Carrier(CarrierID) ON DELETE CASCADE
);

CREATE TABLE Users(
Username VARCHAR(20),
Password VARCHAR(100) NOT NULL,
AccessLevel INT NOT NULL,
CONSTRAINT PRIMARY KEY (Username)
);